# Use root/example as user/password credentials
version: '3.1'

services:

  mysql:
    image: mariadb
    restart: always
    volumes:
       - ~/apps/build-server/mysql-server/data:/var/lib/mysql/data
    environment:
      MYSQL_ROOT_PASSWORD: agiledev@2018

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:db
    ports:
      - 8181:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: agiledev@2018
      PMA_HOST: mysql

  sonarqube:
    image: sonarqube
    ports:
      - 9000:9000
      - 9092:9092

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - 8080:8080
      - 5000:5000
    environment:
      jenkins_home: ~/apps/build-server/jenkins
